const hero=document.querySelector('.hero');
const founderImage=document.querySelector('img[alt="Emmanuel Gnanaseelan"]')?.src;
if(hero&&founderImage){
  hero.innerHTML=`<div class="heroSlider" aria-roledescription="carousel" aria-label="Baruch Engineers highlights">
    <div class="heroTrack">
      <section class="heroSlide founderSlide active" aria-hidden="false">
        <div class="slideCopy">
          <p class="eyebrow">Founder-led lubrication engineering</p>
          <h1>The right oil is not a purchase.<br><em>It is a productivity decision.</em></h1>
          <p>Every overheating gearbox, sluggish hydraulic system and premature bearing failure tells a story. We read the operating conditions, identify the lubrication gap and recommend the right path to longer equipment life and dependable production.</p>
          <div class="actions"><a class="btn" href="#contact">Discuss Your Application →</a><a class="btn outline" href="#solutions">Explore Solutions</a></div>
          <span class="region">Emmanuel Gnanaseelan · Founder & Industrialist</span>
        </div>
        <div class="founderVisual"><img src="${founderImage}" alt="Emmanuel Gnanaseelan, founder of Baruch Engineers"><div class="founderBadge"><b>Emmanuel Gnanaseelan</b><span>Founder &amp; Industrialist</span></div></div>
      </section>
      <section class="heroSlide" aria-hidden="true">
        <div class="slideCopy"><p class="eyebrow">Industrial performance. Engineered.</p><h1>Less friction.<br>Less downtime.<br><em>More output.</em></h1><p>A lubricant must do more than meet a grade. It must control heat, maintain film strength, resist contamination and perform through the real duty cycle of your machine.</p><div class="actions"><a class="btn" href="#finder">Find the Right Lubricant →</a><a class="btn outline" href="#contact">Talk to an Expert</a></div></div>
        <div class="slideMetric"><div><b>Control heat</b><span>Maintain stable viscosity under demanding temperatures</span></div><div><b>Reduce wear</b><span>Protect loaded gears, bearings and hydraulic components</span></div><div><b>Extend life</b><span>Support cleaner oil and longer service intervals</span></div></div>
      </section>
    </div>
    <div class="heroNav"><button class="heroDot active" aria-label="Show slide 1"></button><button class="heroDot" aria-label="Show slide 2"></button><span class="heroCounter">01 / 02</span><div class="heroArrows"><button class="heroArrow heroPrev" aria-label="Previous slide">←</button><button class="heroArrow heroNext" aria-label="Next slide">→</button></div></div>
  </div>`;
  const slides=[...hero.querySelectorAll('.heroSlide')],dots=[...hero.querySelectorAll('.heroDot')],counter=hero.querySelector('.heroCounter');let heroIndex=0,heroTimer;
  const showHero=i=>{heroIndex=(i+slides.length)%slides.length;slides.forEach((s,n)=>{s.classList.toggle('active',n===heroIndex);s.setAttribute('aria-hidden',n!==heroIndex)});dots.forEach((d,n)=>d.classList.toggle('active',n===heroIndex));counter.textContent=`0${heroIndex+1} / 0${slides.length}`;clearInterval(heroTimer);heroTimer=setInterval(()=>showHero(heroIndex+1),6500)};
  dots.forEach((d,n)=>d.addEventListener('click',()=>showHero(n)));hero.querySelector('.heroPrev').addEventListener('click',()=>showHero(heroIndex-1));hero.querySelector('.heroNext').addEventListener('click',()=>showHero(heroIndex+1));hero.addEventListener('mouseenter',()=>clearInterval(heroTimer));hero.addEventListener('mouseleave',()=>{heroTimer=setInterval(()=>showHero(heroIndex+1),6500)});showHero(0);
}

const issue={heat:["Oil Overheating","High oil temperature can accelerate degradation, increase wear and affect machine accuracy."],use:["Excessive Consumption","Leakage, unsuitable viscosity or operating conditions may be increasing lubricant use."],wear:["Tool Wear","Fluid condition, concentration and heat management can affect tool performance and surface finish."],pressure:["Hydraulic Pressure Loss","Viscosity, aeration, leakage or contamination may affect hydraulic response."],rust:["Rust & Corrosion","Moisture, handling and insufficient protection may expose components to corrosion."],break:["Frequent Breakdowns","Repeated failures deserve a wider review of lubrication, contamination and maintenance practices."]};document.querySelectorAll('.problem').forEach(b=>b.onclick=()=>{document.querySelectorAll('.problem').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#issueTitle').textContent=issue[b.dataset.key][0];document.querySelector('#issueText').textContent=issue[b.dataset.key][1]});const industryText={"CNC & VMC Machining":"Stable surface finish, heat control, tool performance and machining consistency depend on the right metalworking fluids and process oils.","Precision Engineering":"Protect tolerances, surface quality and production consistency with application-aligned lubrication.","Quarry & Crusher":"Heavy loads, dust and shock demand robust protection for gears, bearings and hydraulic systems.","Fleet & Transportation":"Support engine cleanliness, fuel efficiency and dependable fleet operation.","Textile Machinery":"Maintain clean, smooth and reliable operation across high-speed textile equipment.","Construction & Earthmoving":"Protect engines, hydraulics and drivetrains under heat, load and contamination.","Power & Infrastructure":"Support dependable equipment performance across demanding operating cycles."};document.querySelectorAll('.industry').forEach(b=>b.onclick=()=>{document.querySelectorAll('.industry').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#industryTitle').textContent=b.dataset.industry;document.querySelector('#industryText').textContent=industryText[b.dataset.industry]});document.querySelector('.menu').onclick=()=>document.querySelector('.links').classList.toggle('open');const perfCards=[...document.querySelectorAll('.perfCard')];let perfIndex=0;function focusPerf(i){perfIndex=(i+perfCards.length)%perfCards.length;perfCards.forEach((c,n)=>c.classList.toggle('active',n===perfIndex))}document.querySelector('.perfArrow.next')?.addEventListener('mouseenter',()=>focusPerf(perfIndex+1));document.querySelector('.perfArrow.prev')?.addEventListener('mouseenter',()=>focusPerf(perfIndex-1));document.querySelector('.perfArrow.next')?.addEventListener('click',()=>focusPerf(perfIndex+1));document.querySelector('.perfArrow.prev')?.addEventListener('click',()=>focusPerf(perfIndex-1));

/* Ecommerce first release: catalog, cart, checkout, orders and local admin console. */
(function ecommerce(){
  const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
  const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
  const defaultPrices=[1850,2400,2100,1950,650,1700,980,3200,850,2800];
  const cards=[...document.querySelectorAll('.product')];
  const saved=JSON.parse(localStorage.getItem('baruch_products')||'null');
  let products=saved||cards.map((card,i)=>({id:slug(card.querySelector('h3').textContent),name:card.querySelector('h3').textContent,image:card.querySelector('img').getAttribute('src'),price:defaultPrices[i]||1500,stock:25,active:true}));
  const cart=JSON.parse(localStorage.getItem('baruch_cart')||'{}');
  const save=()=>{localStorage.setItem('baruch_products',JSON.stringify(products));localStorage.setItem('baruch_cart',JSON.stringify(cart));};
  const root=document.createElement('div');root.id='shopApp';root.innerHTML=`<button class="shopCartButton" aria-label="Open cart">Cart <span>0</span></button><div class="shopOverlay" hidden><div class="shopDrawer" role="dialog" aria-label="Shopping cart"><div class="shopDrawerHead"><h2>Your cart</h2><button class="shopClose" aria-label="Close">×</button></div><div class="cartItems"></div><div class="cartFoot"><div><span>Subtotal</span><strong class="cartTotal">₹0</strong></div><button class="btn checkoutOpen">Proceed to checkout</button></div></div></div><div class="checkoutOverlay" hidden><div class="shopModal"><button class="shopClose" aria-label="Close">×</button><div class="checkoutView"></div></div></div><div class="adminOverlay" hidden><div class="shopModal adminModal"><button class="shopClose" aria-label="Close">×</button><div class="adminView"></div></div></div>`;document.body.append(root);
  const cartBtn=root.querySelector('.shopCartButton'),overlay=root.querySelector('.shopOverlay'),checkout=root.querySelector('.checkoutOverlay'),adminOverlay=root.querySelector('.adminOverlay');
  const open=(el)=>{el.hidden=false;document.body.classList.add('shopLocked')};const close=(el)=>{el.hidden=true;document.body.classList.remove('shopLocked')};
  function renderCards(){cards.forEach(card=>{const id=slug(card.querySelector('h3').textContent),p=products.find(x=>x.id===id);if(!p||!p.active){card.hidden=true;return}card.hidden=false;card.dataset.productId=id;let meta=card.querySelector('.shopMeta');if(!meta){meta=document.createElement('div');meta.className='shopMeta';card.querySelector('.productContent').append(meta)}meta.innerHTML=`<span class="shopPrice">${money(p.price)}</span><span class="shopStock">${p.stock>0?`${p.stock} available`:'Out of stock'}</span><button class="addToCart" ${p.stock<1?'disabled':''}>Add to cart</button>`;meta.querySelector('button').onclick=()=>add(id)});}
  function add(id){cart[id]=(cart[id]||0)+1;const p=products.find(x=>x.id===id);if(cart[id]>p.stock)cart[id]=p.stock;save();renderCart();open(overlay)}
  function renderCart(){const ids=Object.keys(cart).filter(id=>cart[id]>0),items=root.querySelector('.cartItems');let total=0,count=0;items.innerHTML=ids.length?ids.map(id=>{const p=products.find(x=>x.id===id);if(!p)return '';const qty=cart[id];total+=p.price*qty;count+=qty;return `<div class="cartLine"><img src="${p.image}" alt=""><div><b>${p.name}</b><small>${money(p.price)} each</small><div class="qty"><button data-id="${id}" data-step="-1">−</button><span>${qty}</span><button data-id="${id}" data-step="1">+</button><button class="removeLine" data-id="${id}">Remove</button></div></div><strong>${money(p.price*qty)}</strong></div>`}).join(''):'<p class="emptyCart">Your cart is empty. Choose a lubricant to get started.</p>';root.querySelector('.cartTotal').textContent=money(total);cartBtn.querySelector('span').textContent=count;items.querySelectorAll('.qty button[data-step]').forEach(b=>b.onclick=()=>{const id=b.dataset.id;cart[id]=Math.max(0,(cart[id]||0)+Number(b.dataset.step));if(!cart[id])delete cart[id];save();renderCart()});items.querySelectorAll('.removeLine').forEach(b=>b.onclick=()=>{delete cart[b.dataset.id];save();renderCart()});root.querySelector('.checkoutOpen').disabled=!ids.length;}
  function checkoutView(){const ids=Object.keys(cart).filter(id=>cart[id]>0),total=ids.reduce((sum,id)=>sum+products.find(p=>p.id===id).price*cart[id],0);root.querySelector('.checkoutView').innerHTML=`<p class="eyebrow">Secure order request</p><h2>Where should we deliver?</h2><p class="formNote">Submit your details and our team will confirm availability, freight and delivery timing.</p><form class="checkoutForm"><div class="formGrid"><label>Full name<input name="name" required autocomplete="name"></label><label>Phone number<input name="phone" required type="tel" autocomplete="tel"></label><label class="wide">Email address<input name="email" required type="email" autocomplete="email"></label><label class="wide">Delivery address<textarea name="address" required rows="3"></textarea></label><label>City / district<input name="city" required></label><label>PIN code<input name="pin" required inputmode="numeric"></label></div><div class="checkoutSummary"><span>Order total</span><strong>${money(total)}</strong></div><button class="btn" type="submit">Place order request →</button></form>`;root.querySelector('.checkoutForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const order={id:'BE-'+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),customer:data,items:ids.map(id=>({id,name:products.find(p=>p.id===id).name,qty:cart[id],price:products.find(p=>p.id===id).price})),total,status:'New order'};const orders=JSON.parse(localStorage.getItem('baruch_orders')||'[]');orders.unshift(order);localStorage.setItem('baruch_orders',JSON.stringify(orders));ids.forEach(id=>{products.find(p=>p.id===id).stock=Math.max(0,products.find(p=>p.id===id).stock-cart[id]);delete cart[id]});save();root.querySelector('.checkoutView').innerHTML=`<div class="orderSuccess"><span class="successMark">✓</span><p class="eyebrow">Order request received</p><h2>Thank you, ${data.name.split(' ')[0]}.</h2><p>Your reference is <b>${order.id}</b>. We’ll contact you at ${data.phone} to confirm the order and delivery.</p><button class="btn shopCloseAction">Continue shopping</button></div>`;renderCards();renderCart();root.querySelector('.shopCloseAction').onclick=()=>close(checkout)};}
  function adminLogin(){root.querySelector('.adminView').innerHTML=`<p class="eyebrow">Baruch Engineers</p><h2>Admin login</h2><p class="formNote">Demo credentials: admin@baruchengineers.com / ChangeMe123!</p><form class="adminLogin"><label>Email<input name="email" type="email" value="admin@baruchengineers.com" required></label><label>Password<input name="password" type="password" required></label><p class="loginError" hidden>Incorrect credentials.</p><button class="btn">Sign in to dashboard</button></form>`;root.querySelector('.adminLogin').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(d.email==='admin@baruchengineers.com'&&d.password==='ChangeMe123!')adminDashboard();else root.querySelector('.loginError').hidden=false;};}
  function adminDashboard(){const orders=JSON.parse(localStorage.getItem('baruch_orders')||'[]');root.querySelector('.adminView').innerHTML=`<div class="adminTop"><div><p class="eyebrow">Operations console</p><h2>Admin dashboard</h2></div><button class="adminLogout">Log out</button></div><div class="adminStats"><div><b>${products.length}</b><span>Products</span></div><div><b>${orders.length}</b><span>Orders</span></div><div><b>${orders.filter(o=>o.status==='New order').length}</b><span>Needs action</span></div></div><h3>Manage products</h3><div class="adminProducts">${products.map(p=>`<div class="adminProduct"><img src="${p.image}" alt=""><label>${p.name}<input data-id="${p.id}" data-field="price" type="number" min="0" value="${p.price}"></label><label>Stock<input data-id="${p.id}" data-field="stock" type="number" min="0" value="${p.stock}"></label></div>`).join('')}</div><h3>Recent orders</h3><div class="adminOrders">${orders.length?orders.map(o=>`<article class="adminOrder"><div><b>${o.id}</b><span>${new Date(o.createdAt).toLocaleString()} · ${o.customer.name} · ${money(o.total)}</span><small>${o.items.map(i=>`${i.name} × ${i.qty}`).join(', ')}</small></div><select data-order="${o.id}">${['New order','Confirmed','Processing','Packed','Shipped','Delivered','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></article>`).join(''):'<p class="emptyCart">No orders yet.</p>'}</div>`;root.querySelectorAll('.adminProducts input').forEach(i=>i.onchange=()=>{const p=products.find(x=>x.id===i.dataset.id);p[i.dataset.field]=Math.max(0,Number(i.value));save();renderCards()});root.querySelectorAll('.adminOrders select').forEach(s=>s.onchange=()=>{const os=JSON.parse(localStorage.getItem('baruch_orders')||'[]'),o=os.find(x=>x.id===s.dataset.order);if(o){o.status=s.value;localStorage.setItem('baruch_orders',JSON.stringify(os));adminDashboard()}});root.querySelector('.adminLogout').onclick=adminLogin;}
  const adminButton=document.createElement('button');adminButton.className='adminTrigger';adminButton.textContent='Admin';document.querySelector('.nav').append(adminButton);adminButton.onclick=()=>{adminLogin();open(adminOverlay)};root.querySelectorAll('.shopClose').forEach(b=>b.onclick=()=>close(b.closest('.shopOverlay,.checkoutOverlay,.adminOverlay')));cartBtn.onclick=()=>{renderCart();open(overlay)};root.querySelector('.checkoutOpen').onclick=()=>{checkoutView();close(overlay);open(checkout)};renderCards();renderCart();
})();
document.addEventListener('DOMContentLoaded',()=>{const hero=document.querySelector('.hero');if(!hero||document.querySelector('.storeBanner'))return;const b=document.createElement('section');b.className='storeBanner';b.innerHTML='<div><p class="eyebrow">ONLINE LUBRICANT STORE</p><h2>Gulf products, ready to order.</h2><p>Browse genuine industrial and automotive lubricants, add products to your cart, and request delivery across Chennai and Pondicherry.</p></div><div class="storeActions"><a class="btn" href="products.html">Shop Gulf Products →</a><span>✓ Secure order request &nbsp; ✓ Local delivery</span></div>';hero.insertAdjacentElement('afterend',b)});
document.addEventListener('DOMContentLoaded',()=>{const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('.navCart')){const c=document.createElement('a');c.className='navCart';c.href='products.html';c.setAttribute('aria-label','Open product store');c.innerHTML='🛒 <span>Shop / Cart</span>';nav.querySelector('.links')?.append(c)}document.querySelectorAll('.product').forEach(card=>{card.querySelector('.shopMeta')?.remove();const h=card.querySelector('h3');if(h){card.style.cursor='pointer';card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;location.href='products.html?category='+encodeURIComponent(h.textContent.trim())})}})});

// Rebrand public storefront content while leaving admin/backend labels untouched.
document.addEventListener('DOMContentLoaded',()=>{
  document.title='Gulf Store | Industrial Lubricants';
  const brand=document.querySelector('.brandLogo');
  if(brand){brand.setAttribute('aria-label','Gulf Store home');brand.innerHTML='<span class="gulfBrand">GULF<br><small>ONLINE STORE</small></span>'}
  const founder=document.querySelector('.founderSlide');
  if(founder){founder.innerHTML='<div class="slideCopy"><p class="eyebrow">GULF ONLINE STORE</p><h1>Gulf lubricants.<br>Ready to order.<br><em>Keep machines moving.</em></h1><p>Choose genuine Gulf oils and fluids by application, add them to your cart and request delivery for your workshop or fleet.</p><div class="actions"><a class="btn" href="products.html">Shop Gulf Products →</a><a class="btn outline" href="products.html">Browse Categories</a></div></div><div class="storeHeroVisual" aria-hidden="true"></div>'}
  document.querySelectorAll('img[alt*="Emmanuel" i], .story, .founderVisual, .founderBadge').forEach(el=>el.remove());
  document.querySelectorAll('.slideCopy .eyebrow').forEach(el=>{el.textContent='GULF ONLINE STORE'});
  document.querySelectorAll('.slideCopy h1').forEach((el,i)=>{if(i>0)el.innerHTML='Performance oils.<br>For every duty cycle.<br><em>Order with confidence.</em>'});
  document.querySelectorAll('.slideCopy p:not(.eyebrow)').forEach(el=>{if(/lubricant must|operating conditions|overheating|failure/i.test(el.textContent))el.textContent='Shop genuine Gulf lubricants selected for hydraulic systems, gears, compressors, engines and demanding industrial equipment.'});
  const footer=document.querySelector('footer');
  if(footer){footer.querySelectorAll('a[href*="baruch"],a[href*="90876"]').forEach(a=>a.remove());const first=footer.querySelector('b');if(first)first.textContent='GULF ONLINE STORE';footer.querySelectorAll('.copyright').forEach(p=>p.textContent='Genuine Gulf lubricants. Product selection should match the equipment application.')}
  document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0&&/Baruch|Emmanuel Gnanaseelan|Founder & Industrialist/i.test(el.textContent))el.textContent=el.textContent.replace(/Baruch Engineers/gi,'Gulf Online Store').replace(/Why Baruch/gi,'Why Gulf').replace(/Baruch/gi,'Gulf').replace(/Emmanuel Gnanaseelan\s*[·-]?\s*Founder\s*&\s*Industrialist/gi,'Gulf product specialists')});
  if(location.hostname.endsWith('vercel.app'))document.querySelectorAll('.adminTrigger').forEach(el=>el.remove());
});
