import 'dotenv/config';
import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import mysql from 'mysql2/promise';

const port=Number(process.env.PORT||3000);const sessions=new Map();
const frontendRoot=path.resolve(process.env.FRONTEND_ROOT||'..');
const pool=mysql.createPool({host:process.env.MYSQL_HOST,port:Number(process.env.MYSQL_PORT||3306),database:process.env.MYSQL_DATABASE,user:process.env.MYSQL_USER,password:process.env.MYSQL_PASSWORD,connectionLimit:5});
const json=(res,status,payload)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization'});res.end(JSON.stringify(payload))};
const body=req=>new Promise((resolve,reject)=>{let data='';req.on('data',chunk=>{data+=chunk;if(data.length>1e6)reject(new Error('Payload too large'))});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch(e){reject(e)}})});
const hash=password=>crypto.scryptSync(password,process.env.SESSION_SECRET||'local-development-secret',32).toString('hex');
const auth=req=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');return token&&sessions.has(token)};
const mailer=process.env.SMTP_HOST?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}}):null;
const notifyOrder=async(order,items)=>{if(!mailer){console.log('[email] SMTP not configured; notification skipped for',order.orderNumber);return}const lines=items.map(i=>`${i.name} × ${i.quantity}`).join('\n');const text=`New Baruch Engineers order ${order.orderNumber}\n\nCustomer: ${order.customer.name}\nPhone: ${order.customer.phone}\nEmail: ${order.customer.email}\nDelivery: ${order.customer.address}, ${order.customer.city} - ${order.customer.pin}\n\nItems:\n${lines}\n\nSubtotal: ₹${order.total}`;await mailer.sendMail({from:process.env.SMTP_USER,to:process.env.ORDER_EMAIL||'operations@baruchengineers.com',cc:process.env.ORDER_CC||'info@baruchengineers.com',subject:`New order ${order.orderNumber}`,text});if(order.customer.email)await mailer.sendMail({from:process.env.SMTP_USER,to:order.customer.email,subject:`Order received ${order.orderNumber}`,text:`Thank you for your order.\n\nYour reference is ${order.orderNumber}. We will contact you to confirm delivery.\n\nTotal: ₹${order.total}`})};
async function route(req,res){if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS','access-control-allow-headers':'content-type, authorization'});return res.end()};const url=new URL(req.url,`http://${req.headers.host}`);try{
  if(req.method==='GET'&&!url.pathname.startsWith('/api/')){const requested=url.pathname==='/'?'/index.html':url.pathname;const safe=path.normalize(requested).replace(/^([.][.][\\/])+/, '');const file=path.join(frontendRoot,safe);if(file.startsWith(frontendRoot)&&fs.existsSync(file)&&fs.statSync(file).isFile()){const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.json':'application/json'};res.writeHead(200,{'content-type':types[path.extname(file).toLowerCase()]||'application/octet-stream'});return res.end(fs.readFileSync(file))}}
  if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,service:'baruch-engineers-commerce-api'});
  if(req.method==='GET'&&url.pathname==='/api/products'){const [rows]=await pool.query('SELECT p.id,p.sku,p.name,p.description,p.price,p.stock,p.image_path AS image,c.name AS category,c.slug AS category_slug FROM products p JOIN categories c ON c.id=p.category_id WHERE p.is_active=1 ORDER BY c.name,p.name');return json(res,200,{products:rows})}
  if(req.method==='GET'&&url.pathname==='/api/categories'){const [rows]=await pool.query('SELECT c.id,c.name,c.slug,COUNT(p.id) AS product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id AND p.is_active=1 GROUP BY c.id ORDER BY c.name');return json(res,200,{categories:rows.filter(c=>Number(c.product_count)>0)})}
  if(req.method==='GET'&&url.pathname==='/api/admin/categories'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const [rows]=await pool.query('SELECT c.id,c.name,c.slug,COUNT(p.id) AS product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.id ORDER BY c.name');return json(res,200,{categories:rows})}
  if(req.method==='POST'&&url.pathname==='/api/admin/categories'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const d=await body(req);if(!d.name?.trim())return json(res,400,{error:'Category name is required'});const slug=d.name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');try{const [r]=await pool.execute('INSERT INTO categories(name,slug) VALUES(?,?)',[d.name.trim(),slug]);return json(res,201,{id:r.insertId,name:d.name.trim(),slug})}catch(e){return json(res,400,{error:'Category name already exists'})}}
  const categoryMatch=url.pathname.match(/^\/api\/admin\/categories\/(\d+)$/);if(categoryMatch&&req.method==='PATCH'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const d=await body(req);if(!d.name?.trim())return json(res,400,{error:'Category name is required'});const slug=d.name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');await pool.execute('UPDATE categories SET name=?,slug=? WHERE id=?',[d.name.trim(),slug,categoryMatch[1]]);return json(res,200,{ok:true})}if(categoryMatch&&req.method==='DELETE'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const [[c]]=await pool.query('SELECT COUNT(*) AS n FROM products WHERE category_id=?',[categoryMatch[1]]);if(Number(c.n))return json(res,400,{error:'Reassign or archive products before deleting this category'});await pool.execute('DELETE FROM categories WHERE id=?',[categoryMatch[1]]);return json(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/admin/products'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const d=await body(req);if(!d.name?.trim()||!d.sku?.trim()||!d.categoryId)return json(res,400,{error:'Name, SKU and category are required'});const price=d.price===''||d.price==null?null:Number(d.price);const stock=Number(d.stock||0);if(price!==null&&(!Number.isFinite(price)||price<0)||!Number.isInteger(stock)||stock<0)return json(res,400,{error:'Invalid price or stock'});try{const [r]=await pool.execute('INSERT INTO products(category_id,sku,name,description,price,stock,image_path,is_active) VALUES(?,?,?,?,?,?,?,?)',[d.categoryId,d.sku.trim(),d.name.trim(),d.description||'',price,stock,d.image||null,d.isActive===false?0:1]);return json(res,201,{id:r.insertId})}catch(e){return json(res,400,{error:'SKU already exists or category is invalid'})}}
  if(req.method==='GET'&&url.pathname==='/api/admin/products'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const [rows]=await pool.query('SELECT p.id,p.sku,p.name,p.price,p.stock,p.is_active AS isActive,p.image_path AS image,c.name AS category FROM products p JOIN categories c ON c.id=p.category_id ORDER BY c.name,p.name');return json(res,200,{products:rows})}
  const productMatch=url.pathname.match(/^\/api\/admin\/products\/(\d+)$/);if(req.method==='PATCH'&&productMatch){if(!auth(req))return json(res,401,{error:'Unauthorized'});const d=await body(req);const price=d.price===null||d.price===''?null:Number(d.price);const stock=Number(d.stock);if((price!==null&&(!Number.isFinite(price)||price<0))||!Number.isInteger(stock)||stock<0)return json(res,400,{error:'Invalid price or stock'});await pool.execute('UPDATE products SET price=?,stock=?,is_active=? WHERE id=?',[price,stock,d.isActive===false?0:1,productMatch[1]]);return json(res,200,{ok:true})}
  if(req.method==='DELETE'&&productMatch){if(!auth(req))return json(res,401,{error:'Unauthorized'});await pool.execute('UPDATE products SET is_active=0 WHERE id=?',[productMatch[1]]);return json(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/admin/login'){const d=await body(req);if(d.email!==process.env.ADMIN_EMAIL||hash(d.password||'')!==hash(process.env.ADMIN_PASSWORD||''))return json(res,401,{error:'Invalid credentials'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{email:d.email,createdAt:Date.now()});return json(res,200,{token})}
  if(req.method==='POST'&&url.pathname==='/api/orders'){const d=await body(req);if(!d.customer||!Array.isArray(d.items)||!d.items.length)return json(res,400,{error:'Customer details and items are required'});if(!['Chennai','Pondicherry'].includes(d.customer.city))return json(res,400,{error:'Delivery is currently available in Chennai and Pondicherry only'});const conn=await pool.getConnection();try{await conn.beginTransaction();const ids=d.items.map(i=>Number(i.productId));const [products]=await conn.query(`SELECT id,name,price,stock,reserved_stock FROM products WHERE id IN (${ids.map(()=>'?').join(',')}) AND is_active=1 FOR UPDATE`,ids);const byId=new Map(products.map(p=>[p.id,p]));let subtotal=0;for(const item of d.items){const p=byId.get(Number(item.productId));const q=Number(item.quantity);if(!p||!Number.isInteger(q)||q<1||q>(p.stock-p.reserved_stock))throw new Error(`Product unavailable or insufficient stock: ${item.productId}`);subtotal+=(Number(p.price)||0)*q}const orderNumber='BE-'+Date.now().toString().slice(-8);const [order]=await conn.execute('INSERT INTO orders(order_number,customer_name,customer_email,customer_phone,delivery_address,delivery_city,delivery_pin,subtotal) VALUES(?,?,?,?,?,?,?,?)',[orderNumber,d.customer.name,d.customer.email,d.customer.phone,d.customer.address,d.customer.city,d.customer.pin,subtotal]);for(const item of d.items){const p=byId.get(Number(item.productId));await conn.execute('INSERT INTO order_items(order_id,product_id,product_name,unit_price,quantity) VALUES(?,?,?,?,?)',[order.insertId,p.id,p.name,p.price,item.quantity]);await conn.execute('UPDATE products SET reserved_stock=reserved_stock+? WHERE id=?',[item.quantity,p.id])}await conn.commit();return json(res,201,{orderNumber,total:subtotal,status:'New order'})}catch(e){await conn.rollback();return json(res,400,{error:e.message})}finally{conn.release()}}
  if(req.method==='GET'&&url.pathname==='/api/admin/orders'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const [rows]=await pool.query('SELECT * FROM orders ORDER BY created_at DESC');const orders=[];for(const row of rows){const [items]=await pool.query('SELECT product_id AS productId,product_name AS name,unit_price AS price,quantity AS qty FROM order_items WHERE order_id=? ORDER BY id',[row.id]);orders.push({...row,items})}return json(res,200,{orders})}
  const statusMatch=url.pathname.match(/^\/api\/admin\/orders\/([^/]+)\/status$/);if(req.method==='PATCH'&&statusMatch){if(!auth(req))return json(res,401,{error:'Unauthorized'});const d=await body(req);const allowed=['New order','Confirmed','Processing','Packed','Shipped','Delivered','Cancelled'];if(!allowed.includes(d.status))return json(res,400,{error:'Invalid order status'});await pool.execute('UPDATE orders SET status=? WHERE order_number=?',[d.status,statusMatch[1]]);return json(res,200,{ok:true})}
  const payMatch=url.pathname.match(/^\/api\/admin\/orders\/([^/]+)\/payment$/);if(req.method==='PATCH'&&payMatch){if(!auth(req))return json(res,401,{error:'Unauthorized'});const d=await body(req);if(!['Pending','Paid','Failed','Refunded'].includes(d.paymentStatus))return json(res,400,{error:'Invalid payment status'});const conn=await pool.getConnection();try{await conn.beginTransaction();const [[o]]=await conn.query('SELECT id,payment_status FROM orders WHERE order_number=? FOR UPDATE',[payMatch[1]]);if(!o)throw Error('Order not found');if(o.payment_status!=='Paid'&&d.paymentStatus==='Paid'){const [items]=await conn.query('SELECT product_id,quantity FROM order_items WHERE order_id=?',[o.id]);for(const i of items)await conn.execute('UPDATE products SET stock=stock-?,reserved_stock=reserved_stock-? WHERE id=? AND reserved_stock>=? AND stock>=?',[i.quantity,i.quantity,i.product_id,i.quantity,i.quantity])}if(o.payment_status!=='Paid'&&d.paymentStatus!=='Paid'&&['Cancelled','Refunded'].includes(d.paymentStatus)){const [items]=await conn.query('SELECT product_id,quantity FROM order_items WHERE order_id=?',[o.id]);for(const i of items)await conn.execute('UPDATE products SET reserved_stock=reserved_stock-? WHERE id=? AND reserved_stock>=?',[i.quantity,i.product_id,i.quantity])}await conn.execute('UPDATE orders SET payment_status=? WHERE id=?',[d.paymentStatus,o.id]);await conn.commit();return json(res,200,{ok:true})}catch(e){await conn.rollback();return json(res,400,{error:e.message})}finally{conn.release()}}
  return json(res,404,{error:'Not found'});
}catch(e){console.error(e);return json(res,500,{error:'Server error'})}}
http.createServer((req,res)=>route(req,res)).listen(port,()=>console.log(`Commerce API listening on http://localhost:${port}`));
